// C4D-DialogResource
DIALOG ctm_dlg_settings
{
  NAME IDS_DIALOG_SETTINGS; CENTER_V; CENTER_H; 
  
  GROUP IDC_GROUP_WRAPPER
  {
    NAME IDS_GROUP_WRAPPER; CENTER_V; SCALE_H; 
    BORDERSIZE 4, 10, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_GROUP_SETTINGS
    {
      NAME IDS_GROUP_SETTINGS; CENTER_V; SCALE_H; 
      BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC_CHANNEL { NAME IDS_STATIC_CHANNEL; CENTER_V; ALIGN_RIGHT; }
      COMBOBOX IDC_COMBO_CHANNEL
      {
        ALIGN_TOP; SCALE_H; 
        CHILDS
        {
          1, IDS_COLOR; 
          2, IDS_LUMINANCE; 
        }
      }
      STATICTEXT IDC_STATIC_SOURCE { NAME IDS_STATIC_SOURCE; CENTER_V; ALIGN_RIGHT; }
      COMBOBOX IDC_COMBO_SOURCE
      {
        ALIGN_TOP; SCALE_H; 
        CHILDS
        {
          1, IDS_LAYER; 
          2, IDS_OBJECT; 
        }
      }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_SETTINGS2
    {
      NAME IDS_GROUP_SETTINGS2; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      CHECKBOX IDC_CHECK_CHILDREN { NAME IDS_CHECK_CHILDREN; CENTER_V; ALIGN_LEFT;  }
      CHECKBOX IDC_CHECK_CLEARPREV { NAME IDS_CHECK_CLEARPREV; CENTER_V; ALIGN_LEFT;  }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_BUTTONS
    {
      NAME IDS_GROUP_BUTTONS; CENTER_V; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      BUTTON IDC_BUTTON_CANCEL { NAME IDS_BUTTON_CANCEL; ALIGN_TOP; ALIGN_LEFT; }
      BUTTON IDC_BUTTON_DOIT { NAME IDS_BUTTON_DOIT; ALIGN_TOP; ALIGN_LEFT; }
    }
  }
}